name: keyboard_actions
description: Now you can add features to the Android / iOS keyboard in a very simple way. 
version: 3.4.0
homepage: https://github.com/diegoveloper/
repository: https://github.com/diegoveloper/flutter_keyboard_actions/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc_analytics:
    git:
      url: https://github.com/mateusfsilva/flutter_bloc_analytics.git
      ref: 87988be994dcc880919e63dc03cd4fc0222dffb3
      path: packages/bloc_analytics

dev_dependencies:
  lint: ^1.5.3

flutter: